[package]
name = "metro-schedule-api"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
csv = "1.0"
rust-embed = "4.3"