[package]
name = "metro-schedule-api"
version = "0.1.0"
authors = ["Bryant Deters <bryantdeters@gmail.com"]

[dependencies]
actix-web = "1.0"
clap = "2.33.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
csv = "1.0"
rust-embed = "4.4"
